- name: BLOCK WITH NIX TAG
  tags: nix
  become: "yes"
  become_user: "{{ user['name'] }}"
  block:
    - name: RETRIEVE USER HOME DIRECTORY
      ansible.builtin.shell:
        cmd: echo "$HOME"
      register: _user_home
      changed_when: false

    - name: "NIXPKGS CHANNEL CONFIGURED FOR {{ user['name'] }}"
      ansible.builtin.command:
        argv:
          - /usr/bin/nix-channel
          - --add
          - https://nixos.org/channels/nixpkgs-unstable
        creates: "{{ (_user_home['stdout'], '.nix-channels') | path_join }}"

    - name: NIX CHANNELS UPDATED AND NIXPKGS IS PRESENT
      ansible.builtin.command:
        argv:
          - /usr/bin/nix-channel
          - --update
        creates: >-
          {{ (_user_home['stdout'], '.nix-defexpr/channels/nixpkgs/.version')
             | path_join
          }}

    - name: >-
        NIX PACKAGES {{ user['nix_packages'] | join(', ') }}
        INSTALLED FOR {{ user['name'] }}
      nix:
        name: "{{ item }}"
        state: present
        attr: "yes"
      loop: "{{ user['packages'] }}"
